---
- name: Scale up resources
  hosts: 172.17.204.8
  vars:
    namespace: robot-shop
    command:
      - "stress"
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
    label: "app: robot-shop"
    name: app-review
    image: polinux/stress
    kubeconfig_path: "~/.kube/config"

  tasks:
    - name: Extract extra_vars from POST request body
      set_fact:
        extra_vars: "{{ request_body | default({}) }}"
      when: request_body is defined

    - name: Get memory_request and memory_limit from extra_vars
      set_fact:
        memory_request: "{{ extra_vars.memory_request | default('150Mi') }}"
        memory_limit: "{{ extra_vars.memory_limit | default('200Mi') }}"

    - name: Get the status of app-review pod in robot-shop namespace and register output in var pod_info
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig_path }}"
        api_version: v1
        kind: Pod
        label_selectors:
          - app=robot-shop
        namespace: "{{ namespace }}"
        name: app-review
      register: pod_info

    - name: Display the pod_info
      ansible.builtin.debug:
        var: pod_info

    - name: Delete pod app-review in robot-shop namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        api_version: v1
        kind: Pod
        label_selectors:
          - app=robot-shop
        namespace: "{{ namespace }}"
        name: app-review

    - name: Wait for 30 sec
      ansible.builtin.wait_for:
        timeout: 30

    - name: Create app-review pod using a container from image var with dynamic memory resource request and limit and var command and args
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: app-review
            namespace: "{{ namespace }}"
          spec:
            containers:
              - name: app-review
                image: "{{ image }}"
                resources:
                  requests:
                    memory: "{{ memory_request }}"
                  limits:
                    memory: "{{ memory_limit }}"
                command: "{{ command }}"
                args: "{{ args }}"
